version: '3'

services:
  pesapi-app:
    image: node:22.7.0
    container_name: pesapi-app
    volumes:
      - .:/app
    environment:
      NODE_ENV: development
    command: ['sleep', 'infinity']
    depends_on:
      - pesapi-db
    restart: unless-stopped
    networks:
      - pesapi
  pesapi-db:
    image: mysql:9.0.1
    container_name: pesapi-db
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: yes
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    restart: unless-stopped
    networks:
      - pesapi
  pesapi-phpmyadmin:
    image: phpmyadmin:5.2.1
    container_name: pesapi-phpmyadmin
    environment:
      PMA_HOST: pesapi-db
      PMA_USER: ${DB_USER}
      PMA_PASSWORD: ${DB_PASSWORD}
    restart: unless-stopped
    ports:
      - 8080:80
    networks:
      - pesapi
volumes:
  db:
networks:
  pesapi:
