version: '3'

services:
  app:
    image: node:20.10.0
    container_name: app
    volumes:
      - .:/app
    environment:
      NODE_ENV: development
    command: ['sleep', 'infinity']
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - pesapi
  db:
    image: mysql:8.2.0
    container_name: db
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: yes
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    restart: unless-stopped
    networks:
      - pesapi
volumes:
  db:
networks:
  pesapi:
